services:
  pedagogico:
    build: .
    container_name: pedagogico
    restart: always

    environment:
      - SECRET_KEY=${SECRET_KEY:-altere-em-producao}
      - APPLICATION_ROOT=/pedagogico
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/pedagogico.db
      - PROXY_FIX=1
      - GENERIC_TIMEZONE=America/Fortaleza

    ports:
      - "5023:5023"
      
    volumes:
      - pedagogico_data:/app/data

    networks:
      - proxy

volumes:
  pedagogico_data:

networks:
  proxy:
    external: true
